Fix issue when creating the new maven index job
It's probably missing its parent.

```
jenkins.JenkinsException: Cannot create job[DLSMAVEXP/build-and-push] because folder for the job does not exist
```

Related to T4105